# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-22 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_auto_20190122_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
