# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-22 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_auto_20190122_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
